We will be using Linear Regression to advise a (fake) Ecommerce company based in New York City that sells clothing online but they also have in-store style and clothing advice sessions. Customers come in to the store, have sessions/meetings with a personal stylist, then they can go home and order either on a mobile app or website for the clothes they want.

The company is trying to decide whether to focus their efforts on their mobile app experience or their website.

We'll first explore this data, before using Linear Regression to study the correlations between the different factors and how they affect the how much the customer spends.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
from scipy import stats as mystats
import warnings
warnings.filterwarnings('ignore')


In [2]:
df=pd.read_csv('Ecommerce Customers.csv')

In [3]:
df.describe()


Avg. Session Length  Time on App  Time on Website  \
count           500.000000   500.000000       500.000000   
mean             33.053194    12.052488        37.060445   
std               0.992563     0.994216         1.010489   
min              29.532429     8.508152        33.913847   
25%              32.341822    11.388153        36.349257   
50%              33.082008    11.983231        37.069367   
75%              33.711985    12.753850        37.716432   
max              36.139662    15.126994        40.005182   

       Length of Membership  Yearly Amount Spent  
count            500.000000           500.000000  
mean               3.533462           499.314038  
std                0.999278            79.314782  
min                0.269901           256.670582  
25%                2.930450           445.038277  
50%                3.533975           498.887875  
75%                4.126502           549.313828  
max                6.922689           765.518462

In [4]:
df

Email  \
0        mstephenson@fernandez.com   
1                hduke@hotmail.com   
2                 pallen@yahoo.com   
3          riverarebecca@gmail.com   
4    mstephens@davidson-herman.com   
..                             ...   
495   lewisjessica@craig-evans.com   
496            katrina56@gmail.com   
497             dale88@hotmail.com   
498            cwilson@hotmail.com   
499      hannahwilson@davidson.com   

                                               Address            Avatar  \
0         835 Frank Tunnel\nWrightmouth, MI 82180-9605            Violet   
1       4547 Archer Common\nDiazchester, CA 06566-8576         DarkGreen   
2    24645 Valerie Unions Suite 582\nCobbborough, D...            Bisque   
3     1414 David Throughway\nPort Jason, OH 22070-1220       SaddleBrown   
4    14023 Rodriguez Passage\nPort Jacobville, PR 3...  MediumAquaMarine   
..                                                 ...               ...   
495  4483 Jones Motorway Suite 872\nLake Jamiefurt,...               Tan   
496  172 Owen Divide Suite 497\nWest Richard, CA 19320     PaleVioletRed   
497  0787 Andrews Ranch Apt. 633\nSouth Chadburgh, ...          Cornsilk   
498  680 Jennifer Lodge Apt. 808\nBrendachester, TX...              Teal   
499  49791 Rachel Heights Apt. 898\nEast Drewboroug...       DarkMagenta   

     Avg. Session Length  Time on App  Time on Website  Length of Membership  \
0              34.497268    12.655651        39.577668              4.082621   
1              31.926272    11.109461        37.268959              2.664034   
2              33.000915    11.330278        37.110597              4.104543   
3              34.305557    13.717514        36.721283              3.120179   
4              33.330673    12.795189        37.536653              4.446308   
..                   ...          ...              ...                   ...   
495            33.237660    13.566160        36.417985              3.746573   
496            34.702529    11.695736        37.190268              3.576526   
497            32.646777    11.499409        38.332576              4.958264   
498            33.322501    12.391423        36.840086              2.336485   
499            33.715981    12.418808        35.771016              2.735160   

     Yearly Amount Spent  
0             587.951054  
1             392.204933  
2             487.547505  
3             581.852344  
4             599.406092  
..                   ...  
495           573.847438  
496           529.049004  
497           551.620145  
498           456.469510  
499           497.778642  

[500 rows x 8 columns]

## Checking if our data Set is containing any null values 

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Email                 500 non-null    object 
 1   Address               500 non-null    object 
 2   Avatar                500 non-null    object 
 3   Avg. Session Length   500 non-null    float64
 4   Time on App           500 non-null    float64
 5   Time on Website       500 non-null    float64
 6   Length of Membership  500 non-null    float64
 7   Yearly Amount Spent   500 non-null    float64
dtypes: float64(5), object(3)
memory usage: 31.4+ KB


In [6]:
X=df.iloc[:,3:7]
Y=df.iloc[:,-1]

In [7]:
Y

0      587.951054
1      392.204933
2      487.547505
3      581.852344
4      599.406092
          ...    
495    573.847438
496    529.049004
497    551.620145
498    456.469510
499    497.778642
Name: Yearly Amount Spent, Length: 500, dtype: float64

In [8]:
X

Avg. Session Length  Time on App  Time on Website  Length of Membership
0              34.497268    12.655651        39.577668              4.082621
1              31.926272    11.109461        37.268959              2.664034
2              33.000915    11.330278        37.110597              4.104543
3              34.305557    13.717514        36.721283              3.120179
4              33.330673    12.795189        37.536653              4.446308
..                   ...          ...              ...                   ...
495            33.237660    13.566160        36.417985              3.746573
496            34.702529    11.695736        37.190268              3.576526
497            32.646777    11.499409        38.332576              4.958264
498            33.322501    12.391423        36.840086              2.336485
499            33.715981    12.418808        35.771016              2.735160

[500 rows x 4 columns]

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
X, Y, test_size=0.20, random_state=42)

In [11]:
from sklearn.linear_model import LinearRegression
regresor=LinearRegression().fit(X,Y)
y_pred=regresor.predict(X_test)

In [12]:
y_pred

array([403.00023477, 542.19629058, 426.30648223, 501.79550874,
       409.53955985, 569.64664209, 531.55735138, 505.78864242,
       408.25429025, 473.37717243, 441.02741758, 424.90775556,
       424.84012447, 526.94278922, 430.99821788, 423.61672658,
       575.49634125, 484.56063703, 458.04357262, 481.41559016,
       501.87913239, 513.19032274, 507.33984105, 646.16138229,
       449.83595055, 495.7487319 , 555.73712136, 554.51776695,
       399.1668672 , 325.41823125, 532.31652489, 477.64548274,
       500.61828086, 305.76865897, 505.20013188, 483.40628414,
       518.33556963, 437.83934106, 456.26017429, 470.57024648,
       493.96860627, 445.26118373, 508.40032412, 500.62502813,
       488.5442102 , 534.81311759, 594.73928806, 513.55077024,
       280.33784657, 432.88828376, 421.10472607, 480.92490485,
       584.13766535, 608.31496446, 563.61940427, 494.3049836 ,
       394.2796933 , 456.44518096, 572.52599141, 499.01512976,
       512.60202232, 391.78670773, 479.42982418, 481.19

In [13]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [14]:
print('mae',mean_absolute_error(y_pred,y_test))
print('mse',mean_squared_error(y_pred,y_test))
print('rmse',np.sqrt(mean_squared_error(y_pred,y_test)))


mae 8.491334187188972
mse 108.36577565944879
rmse 10.409888359605437


In [15]:
X_test.shape

(100, 4)

In [16]:
r2=r2_score(y_pred,y_test)

In [17]:
r2

0.9784474466621986

In [18]:
Adjusted_r2_score=1-((1-r2)*(100-1))/(100-1-4)

In [19]:
Adjusted_r2_score

0.9775399707321859

In [ ]:
#we can see our Adj_r2 value is less then our r2_score value

In [20]:
from sklearn.model_selection import cross_val_score

In [21]:
cross_val_score=cross_val_score(regresor, X, Y, cv=10)

In [22]:
cross_val_score.mean()

0.9825492707486994

In [23]:
from sklearn.linear_model import Ridge
clf = Ridge(alpha=1.0)
clf.fit(X_train,y_train)


Ridge()

In [24]:
r_pred=clf.predict(X_test)

In [25]:
r2_score(r_pred,y_test)

0.9782424299312423

In [26]:
print('mae',mean_absolute_error(r_pred,y_test))
print('mse',mean_squared_error(r_pred,y_test))
print('rmse',np.sqrt(mean_squared_error(r_pred,y_test)))


mae 8.539230754571278
mse 109.45504392646647
rmse 10.462076463420944


In [29]:
from sklearn import linear_model


In [32]:
li=[]
for i in [1,2,7,9,15]:
    alpha=i
    loa=linear_model.Lasso(alpha=i)
    loa.fit(X_train,y_train)
    ylpred=loa.predict(X_test)
    Cloa =loa.coef_
    li.append(Cloa)
    print(r2_score(y_test,ylpred))
    

0.9776634203062273
0.9765116640710505
0.9543306714228227
0.9377945692115652
0.8619106901061492


In [33]:
li

[array([24.57367356, 37.82407373,  0.        , 61.01564656]),
 array([23.54820389, 36.83691418,  0.        , 60.14901621]),
 array([18.42091194, 31.90114203,  0.        , 55.81586137]),
 array([16.36999766, 29.92683431,  0.        , 54.08259929]),
 array([10.21725482, 24.00391114,  0.        , 48.88281307])]

In [ ]:
#As we can see if we increase the alpa value our model starts underfitting or 
#we can say our byes is increase and varience is reducing

#coefficient also decreasing 